### ISSUE TITLE
app crashed when running

### ISSUE THREAD

**Issue by YYDD** [matomo-org/matomo-sdk-ios#127]
hi ~
app crashed about coredata

the crash pointed in the function 
- (void)deleteEventsWithIDs:(NSArray*)entityIDs
the line with "    [self.managedObjectContext save:&error];"

thanks for check it.

**Comment by brototyp** [comment]
Hi @YYDD, thanks for your report. Do you have an actual crash report for us to investigate?

**Comment by YYDD** [comment]
Sorry @brototyp  , I have not saved the report. But it happens not offten. I just met it just one time.

**Comment by irou** [comment]
Hi , The same problem ,I have the report.

**Comment by irou** [comment]
This problem occurred 500 times in my app. thanks for check it.
[crash.txt](https://github.com/piwik/piwik-sdk-ios/files/907341/crash.txt)

**Comment by YYDD** [comment]
#131 maybe the change can resolve it.

**Comment by brototyp** [comment]
Since this issue is about a year old and the Swift SDK aged a bit I would recommend to move over to the Swift SDK.
