### ISSUE TITLE
Add support for dependency management using Swift Package Manager

### ISSUE THREAD

**Issue by brototyp** [matomo-org/matomo-sdk-ios#135]

**Comment by brototyp** [comment]
I added experimental SPM support in [this branch](https://github.com/piwik/piwik-sdk-ios/tree/feature/135-spm-support). Please try it out and give feedback on it.

**Comment by nwhittaker** [comment]
Would love to see SPM support released for Xcode 11.

**Comment by raptorxcz** [comment]
Any update? Xcode 11 release is comming 🙂

**Comment by brototyp** [comment]
Hey @raptorxcz, @nwhittaker, I just updated the [branch](https://github.com/piwik/piwik-sdk-ios/tree/feature/135-spm-support) and created a PR (#312). It works for the on a tiny test project. Do you mind giving it a test run?

**Comment by nwhittaker** [comment]
>Do you mind giving it a test run?

@brototyp, I added it to my project and it appears to be working well for me.

**Comment by lgaches** [comment]
@brototyp is working for me too. Do you know when it will be merged?

**Comment by whiskey** [comment]
Hi @brototyp, I see the PR #312 idling around for some time. Is there a reason why this is the case and if so, is there a way I can help to get Swift Packages into the next SDK version? :)

**Comment by brototyp** [comment]
Hey @nwhittaker, @lgaches, @whiskey sorry for not being responsive here. "Real" work was just a bit full in the last time. I appreciate you all being so patient and polite! Thanks for being such great members of the community!

I just added a changelog entry and will merge in a minute. I will also prepare a new release.

**Comment by brototyp** [comment]
This was just released in [version 7.2.0](https://github.com/matomo-org/matomo-sdk-ios/releases/tag/v7.2.0).
