### ISSUE TITLE
Better triggering Event dispatching

### ISSUE THREAD

**Issue by brototyp** [matomo-org/matomo-sdk-ios#139]
Currently events are dispatched every [20 Seconds](https://github.com/piwik/piwik-sdk-ios/blob/develop/PiwikTracker/Tracker.swift#L84) and there are always a [maximum of 20 Events](https://github.com/piwik/piwik-sdk-ios/blob/develop/PiwikTracker/Tracker.swift#L50) dispatched.

Those things should change:

- I think it would be good to trigger the dispatching of event on every App Backgrounding
- Add the possibility to configure the dispatch interval
- Add the possibility to configure the maximum amount of dispatched events at a time. Or is it better to make an educated decision here? Is there really a good reason to change this value?

**Comment by brototyp** [comment]
> I think it would be good to trigger the dispatching of event on every App Backgrounding

I am not sure about this one anymore. I think we should leave this to the user of the sdk. In the end it would be just one line to dispatch on every backgrounding.

**Comment by simonnickel** [comment]
> I think we should leave this to the user of the sdk.

I think this is fine, just doing this btw. Works fine most of the time, but sometimes the request does get killed when taking too long. 

This should be more reliable when the SDK can send using a background URLSession instead of URLSession.shared. Requires some changes on the URLSessionDispatcher though.

**Comment by brototyp** [comment]
That's actually an important idea! I love it! We should do that. Do you want to write a separate ticket for that and we close this one for now?

**Comment by simonnickel** [comment]
> That's actually an important idea! I love it! We should do that. Do you want to write a separate ticket for that and we close this one for now?

Created https://github.com/matomo-org/matomo-sdk-ios/issues/311
