### ISSUE TITLE
Implement an exception handler that automatically track and report non handled exceptions

### ISSUE THREAD

**Issue by mattiaslevin** [matomo-org/matomo-sdk-ios#18]
Install the exception handler in the app and report un uncaught exception thrown by the app.

Should not be installed by default.

GA example
https://developers.google.com/analytics/devguides/collection/ios/v3/exceptions

**Comment by brototyp** [comment]
Since exceptions aren't really recognized as such in the backend I think we should not implement this. Exception tracking and analytics is (currently) better done by others and I think we should stick to the roots.
