### ISSUE TITLE
Exposing the visitorID to Objective-C

### ISSUE THREAD

**Issue by Nick-chen** [matomo-org/matomo-sdk-ios#228]
Missing properties and methods in oc environment.For example,visitorId property and tracking event method

**Comment by brototyp** [comment]
Hi @Nick-chen, thanks for getting in touch. I just created a pull request regarding the `visitorId`. See #229.
Regarding the tracking event method. Do you talk about the `public func track(_ event: Event) {` method? If so, yes you are right. This method is currently not supported in Objective-C. What are you trying to achieve with this method?

**Comment by brototyp** [comment]
This issue got implemented, merged and will be part of the next release
