### ISSUE TITLE
Crash on app launching due to Core Data

### ISSUE THREAD

**Issue by catjia1011** [matomo-org/matomo-sdk-ios#80]
Hi, when we integrated piwik, we came into a problem that some users will crash when they launch the app. Attached is the info from Crashlytics. Hope it can be fixed and there is a new release of Piwik. Thanks!

p.s. We are using 3.3.0, which is released on May.30

[Crash reports.txt](https://github.com/piwik/piwik-sdk-ios/files/38708/Crash.reports.txt)

**Comment by Urkman** [comment]
Same here... No Fix for that?

**Comment by mattab** [comment]
Hi @catjia1011 @Urkman we are currently looking for help maintaining and improving our iOS SDK. if you would like to help please consider opening a pull request! We would be glad for any help to make our iOS SDK better, more stable, and with all features that Piwik Tracking API offers :+1:

**Comment by DaliborK** [comment]
I had the same issue, swift project with piwik added via pod file. The problem was with the location of of the xcdatamodel file. This change in PiwikTracker.m fix the problem "NSURL *modelURL = [[NSBundle mainBundle] URLForResource:@"/Frameworks/PiwikTracker.framework/piwiktracker" withExtension:@"momd"];"

**Comment by MishraVikas1** [comment]
@mattab you hav fix for that?

**Comment by DaliborK** [comment]
That was the error I had. Just change the location of the modelURL in PiwikTracker.m - then you must make note of the change un case you update the pod.

**Comment by MishraVikas1** [comment]
@DaliborK okay thanks.
i fixed by adding resource path on the Pods-Knotalk-resources.h
`  install_resource "PiwikTracker/PiwikTracker/piwiktracker.xcdatamodeld"
`

**Comment by rafalkitta** [comment]
Hi, is the way to fix this crash without modifying Pod? @MishraVikas1 Could you explain in more details how do you fix that?

**Comment by MishraVikas1** [comment]
Hi, there is a coredata file in piwik. Add it to bundle resources.
 Thanks & Regards
Vikas Mishra
DESS Mobility - iOS Developer (ASE)
Tata Consultancy Services Limited
Cell:- +91-8939206940
Mailto: mishra.vikas1@tcs.com
Website: http://www.tcs.com 

 -----Rafa&#322; Kitta <notifications@github.com> wrote: -----

 =======================
 To: piwik/piwik-sdk-ios <piwik-sdk-ios@noreply.github.com>

**Comment by mattab** [comment]
FYI:  we the Piwik team are looking for a maintainer for the iOS SDK. if you can help please comment here #91 - we need you!

**Comment by kuzdu** [comment]
When you implement Piwik as static library not as pod, then this error doesn't occur. I know a static library has cons, but in my case this is the better solution.

**Comment by brototyp** [comment]
Since this is a stale discussion and the new SDK doesn't need any Core Data anymore I will close this issue for now.

**Comment by nograsby** [comment]
Had same problem for second target. Add piwiktracker.xcdatamodeld to compile resources
